Relaunch app action in File menu
sindresorhus/caprine pull request #1410
Opened 2020-09-12 07:04 UTC by kwongtn

As per issues mentioned in 
https://github.com/sindresorhus/caprine/issues/1321#issuecomment-624578500
https://github.com/sindresorhus/caprine/issues/1244

Caprine uses quite a lot of RAM on extended usage, the best way to reclaim RAM is to close and relaunch Caprine.
To relaunch, we had to:
Close Caprine -> Go to taskbar and close caprine again -> Open Caprine

This patch introduces the option to do so directly from the "file" menu, making relaunching a simple click away.

2020-09-29 23:40 UTC, sindresorhus requested changes

2020-09-29 23:40 UTC, sindresorhus commented on source/menu.ts
> +		},
There should be a separator here.

2020-09-29 23:40 UTC, sindresorhus commented on source/menu.ts
> +			label: 'Relaunch App',
This is in the wrong position. Note the variable name of the array.

It should also be named `Relaunch Caprine`.

2020-09-30 05:23 UTC, kwongtn commented
Hi @sindresorhus 
I've done the changes accordingly, please check 😅 

Sorry if this is wrong again -- I'm really very new to ts and electron 😂

2020-10-18 21:47 UTC, merged