Fix "Hide Names and Avatars"
sindresorhus/caprine pull request #1600
Opened 2021-03-30 16:56 UTC by jcabak

I noticed that that option "Hide Names and Avatars" blur only avatars. Propably @fame1219 had the same problem in ussue #1583 

During the tests I also noticed that this option don't work for unread message - don't blur even an avatar.

2021-03-31 08:28 UTC, dusansimic commented
From what I can see, chat name in the top bar and on the right sidebar are still visible. If we want to hide names, then we should hide all of them 😁.

![image](https://user-images.githubusercontent.com/12685466/113114502-b2621500-920b-11eb-9af1-864a0cd50471.png)
![image](https://user-images.githubusercontent.com/12685466/113114526-b7bf5f80-920b-11eb-9a06-1ca0040c401a.png)

2021-03-31 08:34 UTC, dusansimic requested changes

2021-03-31 08:34 UTC, dusansimic commented on css/new-design/browser.css
> +{
This opening bracket should be on the line 31. CSS linter is not working correctly because it's not checking the new design files.

2021-03-31 13:00 UTC, jcabak commented on package.json
> +		"webpack": "^5.28.0"
After `npm install && npm start` I had error and information that I should `npm install --savedev webpack`, but you have right, we don't need that :)

2021-03-31 14:52 UTC, dusansimic requested changes

2021-03-31 14:52 UTC, dusansimic commented on .gitignore
> +mas.provisionprofile
There should be a new line at the end of the file like before.

2021-04-03 10:00 UTC, dusansimic requested changes

2021-04-03 10:00 UTC, dusansimic commented on css/new-design/browser.css
>  html.private-mode [data-pagelet=page] .pfnyh3mw.aovydwv3.j83agx80.h676nmdw.oi9244e8.oygrvhab {
This is broken for the same reason as the sidebar name, classes sometimes differ slightly. This should just patch the problem with sender profile pictures sometimes not being blurred.

```suggestion
html.private-mode [role=main] .pfnyh3mw.aovydwv3.j83agx80 > span {
```

2021-04-06 20:39 UTC, jcabak commented on css/new-design/browser.css
> +html.private-mode [data-pagelet=page] .rq0escxv.l9j0dhe7.du4w35lb.j83agx80.cbu4d94t.g5gj957u.d2edcug0.hpfvmrgz.rj1gh0hx.buofh1pr.p8fzw8mz.pcp91wgn.iuny7tx3.ipjc6fyt {
Weird thing, I don't even see "last active at" label. There is a checkbox to turn it on in Caprine? I even tried to change the language for Messenger but nothing happen.

2021-04-06 20:41 UTC, jcabak commented
I tried your suggestions, it is working for me also. Great that you suggest those changes.

2021-04-06 21:29 UTC, dusansimic commented on css/new-design/browser.css
> +html.private-mode [data-pagelet=page] .rq0escxv.l9j0dhe7.du4w35lb.j83agx80.cbu4d94t.g5gj957u.d2edcug0.hpfvmrgz.rj1gh0hx.buofh1pr.p8fzw8mz.pcp91wgn.iuny7tx3.ipjc6fyt {
I've managed to reproduce behavior you are experiencing. In the preferences window of Caprine, there should be "Turn off/on Active Status" button. I had my active status enabled and once it was disabled, the "last active at" label is hidden. This should show how long ago was someone last active and if they're active right now. That label is blurred because of this class. Just remove this part from CSS and rename, as I've mentioned, the "Sidebar: name" comment to match the description. I'll create a new change suggestion since this PR i practically done 😊.

2021-04-06 21:31 UTC, dusansimic requested changes

2021-04-06 21:31 UTC, dusansimic commented on css/new-design/browser.css
>  }
```suggestion
```

2021-04-06 21:31 UTC, dusansimic commented on css/new-design/browser.css
> + /* Sidebar: name  */
```suggestion
/* Conversation titlebar and sidebar: name */
```

2021-04-06 22:30 UTC, jcabak commented on css/new-design/browser.css
> +html.private-mode [data-pagelet=page] .rq0escxv.l9j0dhe7.du4w35lb.j83agx80.cbu4d94t.g5gj957u.d2edcug0.hpfvmrgz.rj1gh0hx.buofh1pr.p8fzw8mz.pcp91wgn.iuny7tx3.ipjc6fyt {
You are right, I finally managed to turn on Active Status and now I see what was the problem :).

2021-04-08 07:17 UTC, dusansimic approved these changes

2021-04-09 08:32 UTC, merged