Apply dark mode to all new nodes
sindresorhus/caprine pull request #1629
Opened 2021-05-04 19:56 UTC by mquevill

Even if dark mode was set, new nodes (dialogs, etc.) would appear with the `__fb-light-mode` tag, which breaks the theming. I've set up an observer for added nodes and only change ones that have some sort of light mode tag.

This may not be the best or most efficient way to do this, but it seems to apply to most dialogs that I was able to find: Preferences dropdown and overlay, emoji picker, etc.

2021-05-04 20:22 UTC, dusansimic commented
All popup menus seem to be created in `/html/body/div[1]/div/div[1]/div/div[2]/div/div/div[2]/div` and all modals seem to be created in `/html/body/div[1]/div/div[1]/div/div[3]/div`. It might be better to observe just those two elements instead of the whole document and it's subtree. In addition to that, you wouldn't need to observer the subtree at all since the direct children elements have light mode classes.

I'm not sure how much more efficient would it be but at lest it's better than observing the whole tree right from the document element 😊.

2021-05-04 20:25 UTC, dusansimic requested changes

2021-05-04 20:25 UTC, dusansimic commented on source/browser.ts
> +			nodeRecord.addedNodes.forEach(newNode => {
Preferably use `for of` instead of `forEach`.

2021-05-04 21:38 UTC, mquevill commented
I definitely agree that observing the entire tree is not ideal, which is why I was trying to limit it somewhat with attributes.

However, those elements do not exist when starting up Caprine, so it throws an error when trying to observe just those elements. Perhaps calling this observer at a later time in startup would get around this issue? Or there may be a more elegant way to address this.

2021-05-04 22:06 UTC, dusansimic commented
> However, those elements do not exist when starting up Caprine

You could start observing once the [element is ready](https://github.com/sindresorhus/element-ready). It's already being used in Caprine in similar situations.

> Or there may be a more elegant way to address this.

I was thinking that too but in the end settled on creating `observeDarkMode` function 😅. This might be the best solution for now but since now the Messenger website is more dynamic, it seems that we'll need more and more observers to patch the design where required.

2021-05-04 22:18 UTC, dusansimic requested changes

2021-05-04 22:18 UTC, dusansimic commented on source/browser.ts
> +	observerNew.observe(document, {subtree: true, childList: true, attributes: true, attributeFilter: ['addedNodes']});
I'm not sure this attribute filter does anything since `addedNodes` is not an attribute of those elements. By filtering out records you already ignore cases when no new nodes where added.

2021-05-05 15:35 UTC, dusansimic approved these changes

2021-05-05 15:37 UTC, dusansimic commented
Looks good, thanks ✌🏻

2021-05-05 15:49 UTC, dusansimic requested changes
Sorry for the nagging but once I've seen your other pr I've realized the issue with query selector and after that the mixed up variable names 😅

2021-05-05 15:49 UTC, dusansimic commented on source/browser.ts
> +	const menuElements = await elementReady<HTMLElement>('div[class="rq0escxv l9j0dhe7 du4w35lb"] > div:nth-of-type(3) > div', {stopOnDomReady: false});
The query selectors are inverted and I'd prefer using dot notation for classes instead of attribute notation. That way if in some case they are rendered with different order it would still work but with attribute notation it won't.

```suggestion
	const modalElements = await elementReady<HTMLElement>('div.rq0escxv.l9j0dhe7.du4w35lb > div:nth-of-type(3) > div', {stopOnDomReady: false});
```

2021-05-05 15:49 UTC, dusansimic commented on source/browser.ts
> +		observerNew.observe(menuElements, {childList: true});
```suggestion
	if (modalElements) {
		observerNew.observe(modalElements, {childList: true});
```

2021-05-05 15:49 UTC, dusansimic commented on source/browser.ts
> +		observerNew.observe(modalElements, {childList: true});
```suggestion
	const menuElements = await elementReady<HTMLElement>('.j83agx80.cbu4d94t.l9j0dhe7.jgljxmt5.be9z9djy > div:nth-of-type(2) > div', {stopOnDomReady: false});
	if (menuElements) {
		observerNew.observe(menuElements, {childList: true});
```

2021-05-05 16:14 UTC, mquevill commented on source/browser.ts
> +	const menuElements = await elementReady<HTMLElement>('div[class="rq0escxv l9j0dhe7 du4w35lb"] > div:nth-of-type(3) > div', {stopOnDomReady: false});
The issue with the dot notation here is that there are many partial matches to `.rq0escxv.l9j0dhe7.du4w35lb`. Even with an exact match, there are still multiple elements that match. If we rely on the child structure `> div:nth-of-type(3) > div`, then there is only one match, regardless of partial/complete match. However, I was wanting to do an exact match, just in case the structure of partial matches changes later.

With the preferences overlay open:
```javascript
> document.querySelectorAll('.rq0escxv.l9j0dhe7.du4w35lb').length
<- 151
> document.querySelectorAll('div.rq0escxv.l9j0dhe7.du4w35lb').length
<- 132
> document.querySelectorAll('div[class="rq0escxv l9j0dhe7 du4w35lb"]').length
<- 3
```

Going with `'div.rq0escxv.l9j0dhe7.du4w35lb > div:nth-of-type(3) > div'` works for now, but is there a way to avoid partial matches with the dot notation?

2021-05-05 16:24 UTC, dusansimic commented on source/browser.ts
> +	const menuElements = await elementReady<HTMLElement>('div[class="rq0escxv l9j0dhe7 du4w35lb"] > div:nth-of-type(3) > div', {stopOnDomReady: false});
Yeah, you're right. I don't know any good way to use dot notation and exclude partial matches so just leave it with attribute notation and change the variable name 😊.

2021-05-05 16:31 UTC, mquevill commented
> Sorry for the nagging but once I've seen your other pr I've realized the issue with query selector and after that the mixed up variable names

I'd rather things be right before getting merged! I just swapped the query selectors instead of changing the variable names. (Then they stay alphabetical too!)

2021-05-05 16:34 UTC, dusansimic approved these changes

2021-05-07 16:06 UTC, merged