Combine system appearance and dark mode settings
sindresorhus/caprine pull request #1637
Opened 2021-05-10 16:08 UTC by mquevill

The `api.nativeTheme` should work for non-MacOS platforms. This PR combines the `followSystemAppearance` and `darkMode` settings into a `'theme'` configuration setting, which mirrors the `api.nativeTheme.themeSource` variable. However, setting the `'dark'` or `'light'` mode should override the system settings.

I'm not sure if removing the `darkTheme`, which is supposed to force dark mode with _some_ GTK+3 environments, is okay. It could cause some issues with those environments that rely on this configuration.

The theme only updates when you click on the window, but I don't think it should be constantly checking while Caprine is in the background.

Tested on:
- Windows 10, build 19042
- Linux Mint 20.1, Cinnamon DE

2021-05-11 13:49 UTC, mquevill commented on source/menu.ts
> +		},
I was mirroring the emoji selection menu (Native vs FB/Messenger options), but since there are fewer options, I'll just remove the separator.

2021-05-11 14:19 UTC, mquevill commented on source/browser.ts
> +function setThemeMode(): void {
I think "color scheme" sounds like the user is actually choosing colors, whereas a "theme" is a guideline of dark/light and the corresponding colors are already chosen for the user. [This might just be up to each person's connotations of the words.] Using "theme" leaves room for "color scheme" options (e.g. choosing a "red" theme with dark or light mode) to be added in the future. I had debated between `setTheme` and `setThemeMode`, because I feel that `'system'` isn't _really_ a theme. Though I suppose it is just a placeholder for whatever the system has set.

2021-05-11 16:51 UTC, mquevill commented on source/index.ts
> -		darkTheme: isDarkMode, // GTK+3
If it is undefined, Electron will set it as false (since it's only a flag to _force_ dark mode, it doesn't force light mode). So my recent commit simplifies the logic.

2021-05-13 08:32 UTC, dusansimic requested changes

2021-05-13 08:32 UTC, dusansimic commented on source/index.ts
> +	const isDarkMode = config.get('theme') === 'system' ? undefined : config.get('theme') === 'dark';
I think this behavior could be achieved by creating an object instead that would be spread in the window options object. The object would be empty in case `theme` is `system` and it would have `darkTheme` property in case it's either `dark` or `light` (`true` and `false` respectively). That would specify dark theme property in case it's needed and it wouldn't add it at all in case the theme is system. I'd really like if that could be done since it would make it consistent with the system theme at all times (it would need a restart though).

2021-05-13 17:09 UTC, mquevill commented on source/index.ts
> +	const isDarkMode = config.get('theme') === 'system' ? undefined : config.get('theme') === 'dark';
It does not seem like there's a good way to change this after the BrowserWindow has already been created. Perhaps it would only require a restart on platforms that use GTK+ 3? Also, I don't think there's a way to _force_ light mode, if GTK would normally use dark mode for the menubar, since `darkTheme: undefined` is the same as `darkTheme: false`, according to the following lines.

https://github.com/electron/electron/blob/9cf71d72abf97c7583b200063915aa9c8fb23e15/shell/browser/native_window_views.cc#L223-L234
```cc
#if defined(USE_X11)
  if (!features::IsUsingOzonePlatform()) {
    // Start monitoring window states.
    window_state_watcher_ = std::make_unique<WindowStateWatcher>(this);

    // Set _GTK_THEME_VARIANT to dark if we have "dark-theme" option set.
    bool use_dark_theme = false;
    if (options.Get(options::kDarkTheme, &use_dark_theme) && use_dark_theme) {
      SetGTKDarkThemeEnabled(use_dark_theme);
    }
  }
#endif

2021-05-14 13:46 UTC, dusansimic commented on source/index.ts
> +	const isDarkMode = config.get('theme') === 'system' ? undefined : config.get('theme') === 'dark';
I'm not really sure how but I've managed with the first commit in this pr to have the title bar color change once theme is changed from dark to light or the system theme is changed and now I can't get it to work. I'm have no idea what's going on so let's just leave it without the `darkTheme` option (just as it was at the beginning of the pr). Everything else lgtm.

2021-05-14 13:46 UTC, dusansimic approved these changes

2021-05-14 15:20 UTC, mquevill commented on source/index.ts
> +	const isDarkMode = config.get('theme') === 'system' ? undefined : config.get('theme') === 'dark';
Okay, sounds good. Removed in 0dac6db.

2021-05-15 06:16 UTC, merged