Fix messenger group icon color
sindresorhus/caprine pull request #1937
Opened 2022-10-15 14:51 UTC by jrafaelsantana

This patch fixes the messenger group icon color on dark theme.

Before:
![image](https://user-images.githubusercontent.com/18506385/195992855-322c1a46-9cd7-49f4-9d20-b47b12fa52cc.png)

After:
![image](https://user-images.githubusercontent.com/18506385/195992808-3fa73a2c-74bb-470f-84a9-b3af312532fe.png)

2022-10-15 15:16 UTC, dusansimic requested changes
Please add a new line to the end of the file. Everything else looks perfect 😁.

2022-10-15 15:17 UTC, dusansimic requested changes

2022-10-15 15:17 UTC, dusansimic commented on css/dark-mode.css
> +/* Messenger Group icon */
```suggestion
/* Create room icon color */
```

2022-10-15 17:07 UTC, jrafaelsantana commented
Done!
Could you tag this PR with the hacktoberfest-accepted label?

Thank you!

2022-10-15 20:31 UTC, dusansimic approved these changes

2022-10-15 20:31 UTC, dusansimic commented
> Could you tag this PR with the hacktoberfest-accepted label?

Of course! Just wanted to make sure everything is in order. I'll merge it when CI passes.

2022-10-15 20:50 UTC, dusansimic commented
@jrafaelsantana could your resolve the conflict?

2022-10-16 10:07 UTC, merged

2022-10-16 10:08 UTC, dusansimic commented
Thanks for the fix!