Fix "Join room" background button
sindresorhus/caprine pull request #1938
Opened 2022-10-15 15:07 UTC by jrafaelsantana

This patch fixes the background color of "Join room" notification button.

Before:
![image](https://user-images.githubusercontent.com/18506385/195993668-362f85f7-e20f-42f9-8e3b-b3a27aa8e8ed.png)

After:
![image](https://user-images.githubusercontent.com/18506385/195993640-37cde4cb-8f48-451f-bd4d-602bfbcc511e.png)

2022-10-15 15:24 UTC, dusansimic requested changes
Also add a new line to the end of file.

2022-10-15 15:24 UTC, dusansimic commented on css/dark-mode.css
> +	background-color: var(--container-color);
What about secondary button background color? It might look better in this case. The darker button on a lighter widget which is itself on a darker background seems kind of out of place.

```suggestion
	background-color: var(--secondary-button-background);
```

2022-10-15 17:11 UTC, jrafaelsantana commented
Done!

Could you tag this PR with the hacktoberfest-accepted label?

Thank you

2022-10-15 20:49 UTC, dusansimic commented
There was an issue with the variable I recommended, it was overwritten by inline css on the frontend (bug in the website, not our fault). Once it was reset to regular variable value it works as expected. This however means you didn't check weather it works after applying the patch I recommended 😁 but it's fine, the important thing is that it's fixed.

2022-10-15 20:49 UTC, dusansimic approved these changes

2022-10-15 20:50 UTC, merged

2022-10-16 00:11 UTC, jrafaelsantana commented
Even after your fix, the background still the wrong color.

![Before](https://user-images.githubusercontent.com/18506385/196011980-0051b5b8-d700-49a0-b098-5ab82b77f100.png)

I made a fix based on your commit. Just fixed the css selectors.

![image](https://user-images.githubusercontent.com/18506385/196011994-690af80e-4f73-4a9c-8ba4-08d7ecdcb904.png)