Dark mode
sindresorhus/caprine pull request #1943
Opened 2022-10-16 13:45 UTC by Anuran12

#1936 

@dusansimic

2022-10-16 13:56 UTC, dusansimic requested changes

2022-10-16 13:56 UTC, dusansimic commented on css/dark-mode.css
> +html.dark-mode .x1qhmfi1 {
This class name is already redefined directly above. In this case you shouldn't hardcode the color, rather patch some other class which is causing the issue. Secondary button background variable is using `rgba(255,255,255,.1)` so that would mean that it's transparent to some degree and there is another element whose background color is light and is causing the button to be light. You'll need to find that element and redefine it's background color.

2022-10-16 13:58 UTC, Anuran12 commented on css/dark-mode.css
> +html.dark-mode .x1qhmfi1 {
ohh okay. got it.

2022-10-16 14:45 UTC, Anuran12 commented
@dusansimic  Sorry I am unable to find that :-(

2022-10-17 10:59 UTC, dusansimic commented
That's fine :) I'll close this pr so someone else can work on it.

2022-10-17 10:59 UTC, closed without merging