Tray icon/indicator Fix
sindresorhus/caprine pull request #2041
Opened 2023-07-28 23:57 UTC by stkrknds

Hello this is a fix for the tray icon/indicator issue. After running the tests, I got an error about putting await inside of a loop. So unfortunately, I had to change the selector of the sidebar and remove the loop. 

Fixes #1995, #1825(partially, still no notifications), #1823, #2031.

2023-08-23 09:45 UTC, dusansimic requested changes

2023-08-23 09:45 UTC, dusansimic commented on source/browser/conversation-list.ts
> +	const chatsIcon = await elementReady(chatsIconSelector, {
```suggestion
	const chatsIcon = await elementReady(selectors.chatsIcon, {
```

2023-08-23 09:45 UTC, dusansimic commented on source/browser/conversation-list.ts
> +		});
This probably won't be very efficient but let's say it's fine for now.

It would be better to monitor the chat icon directly for attribute changes (since that's where you're extracting the number from). That would use far less resources than monitoring the whole chat list.

This could be addressed in a second pr.

2023-08-23 09:45 UTC, dusansimic commented on source/browser/selectors.ts
> +	chatsIcon: '[class="x1i10hfl xjqpnuy xa49m3k xqeqjp1 x2hbi6w x13fuv20 xu3j5b3 x1q0q8m5 x26u7qi x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x1ypdohk xdl72j9 x2lah0s xe8uvvx x2lwn1j xeuugli x4uap5 xkhd6sd
Add a comment that would suggest to check this selector if the tray icon breaks.

```suggestion
	chatsIcon: '[class="x1i10hfl xjqpnuy xa49m3k xqeqjp1 x2hbi6w x13fuv20 xu3j5b3 x1q0q8m5 x26u7qi x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x1ypdohk xdl72j9 x2lah0s xe8uvvx x2lwn1j xeuugli x4uap5 xkhd6sd x1n2onr6 x16tdsg8 x1hl2dhg xggy1nq x1ja2u2z x1t137rt x87ps6o x1lku1pv x1a2a7pz x6s0dn4 x1q0g3np xn3w4p2 x1nn3v0j x1120s5i x1av1boa x1lq5wgf xgqcy7u x30kzoy x9jhf4c xdj266r x11i5rnm xat24cr x1mh8g0r x78zum5"]', # ! Tray icon dependency
```

2023-08-23 09:46 UTC, dusansimic commented
Thanks @stkrknds for the contribution! I've suggested some changes so once they're implemented, we can merge this.

2023-08-23 12:16 UTC, stkrknds commented on source/browser/conversation-list.ts
> +		});
Hello @dusansimic. This is a simple change, do you want me to change that here instead of opening a new pr?

2023-08-24 11:27 UTC, stkrknds commented
I have made some changes, so that only the left sidebar is observed for the chats icon. I think that's the best that can be done in terms of efficiency. The only downside is that there is now an additional selector(for the left sidebar) which may break in the future.

2023-09-02 08:53 UTC, dusansimic commented
> The only downside is that there is now an additional selector(for the left sidebar) which may break in the future.

That is true, but I think it's better to have a new selector that can be fixed than having one more mutation observer that checks a lot of elements on the page for changes. That would consume more resources and in turn make Caprine slower and more resource hungry which is already an issue. I think the path forward is either optimizing existing observer or removing them altogether.

2023-09-02 08:53 UTC, dusansimic approved these changes

2023-09-02 08:53 UTC, merged